# Generated by Django 6.0.1 on 2026-01-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobry', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('BOBR', 'Dodano bobra'), ('OBS', 'Dodano obserwację')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bobr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bobry.bobr')),
                ('obserwacja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bobry.obserwacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
