# Generated by Django 6.0.1 on 2026-01-29 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobry', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
