# Generated by Django 6.0.1 on 2026-01-29 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobry', '0004_bobr_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeremie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('BOBR', 'Dodano bobra'), ('OBS', 'Dodano obserwację'), ('ZER', 'Zbudowano żeremie')], max_length=10),
        ),
    ]
