# Generated by Django 6.0.1 on 2026-01-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobry', '0006_activity_zeremie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeremie',
            name='gatunek_drzewa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='zeremia', to='bobry.gatunekdrzewa'),
            preserve_default=False,
        ),
    ]
